package agile;

import com.formdev.flatlaf.themes.FlatMacLightLaf;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
// Import thư viện để bo cong góc
import java.awt.AlphaComposite;
import java.awt.Color;
import java.awt.Component;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.Insets;
import java.awt.geom.RoundRectangle2D;
import java.io.EOFException;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTextField;
import javax.swing.border.AbstractBorder;
import javax.swing.border.MatteBorder;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.UIManager;
import javax.swing.filechooser.FileNameExtensionFilter;

//// Bo cong góc -----------------------------------------------------------------
//class RoundBorder implements Border {
//    private int radius;
//
//    RoundBorder(int radius) {
//        this.radius = radius;
//    }
//
//    @Override
//    public void paintBorder(Component c, Graphics g, int x, int y, int width, int height) {
//        g.setColor(Color.BLACK); // Màu viền
//        g.drawRoundRect(x, y, width - 1, height - 1, radius, radius);
//    }
//
//    @Override
//    public Insets getBorderInsets(Component c) {
//        return new Insets(radius + 1, radius + 1, radius + 2, radius);
//    }
//
//    @Override
//    public boolean isBorderOpaque() {
//        return true;
//    }
//}
class RoundedCornerBorder extends AbstractBorder {

    private int radius;

    RoundedCornerBorder(int radius) {
        this.radius = radius;
    }

    @Override
    public void paintBorder(Component c, Graphics g, int x, int y, int width, int height) {
        Graphics2D g2d = (Graphics2D) g.create();
        g2d.setColor(new Color(0, 0, 0, 100)); // Màu đen với alpha (độ trong suốt) là 100
        g2d.setComposite(AlphaComposite.SrcOver.derive(0.5f)); // Độ trong suốt của viền

        RoundRectangle2D roundRect = new RoundRectangle2D.Float(x, y, width - 1, height - 1, radius, radius);
        g2d.draw(roundRect);
        g2d.dispose();
    }

    @Override
    public Insets getBorderInsets(Component c) {
        return new Insets(radius, radius, radius, radius);
    }

    @Override
    public boolean isBorderOpaque() {
        return false;
    }
}

//------------------------------------------------------------------------------
public class QuanLyDiemView extends javax.swing.JFrame {

    /**
     * Creates new form QuanLyDiemView
     */
    //ok tri sua xong
    DefaultTableModel defaultTableModel;
    QLSV qlsv = new QLSV();

    public QuanLyDiemView() {
        initComponents();
        ArrayList<SinhVien> list = qlsv.getListSinhVien();
        lblDong.setText(LayThongTinTable(0, list.size()));
        loadData(list);
        
        
        try {
            // TODO add your handling code here:
            docFile();
        } catch (IOException ex) {
            Logger.getLogger(QuanLyDiemView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(QuanLyDiemView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public String LayThongTinTable(int viTriBanDau, int TongSoBanGhi) {
        return (viTriBanDau + 1) + " of " + TongSoBanGhi;
    }

    void loadData(ArrayList<SinhVien> list) {
        defaultTableModel = (DefaultTableModel) tblSinhVien.getModel();
        defaultTableModel.setRowCount(0);
        int stt = 1;
        double total;
        for (SinhVien sinhVien : list) {
            defaultTableModel.addRow(new Object[]{
                stt,
                sinhVien.getMaHS(),
                sinhVien.getTenHS(),
                sinhVien.getGioiTinh(),
                sinhVien.getNamSinh(),
                sinhVien.getQueQuan(),
                sinhVien.getDiemToan(),
                sinhVien.getDiemAnh(),
                sinhVien.getDiemVan(),
                total = (sinhVien.getDiemToan() + sinhVien.getDiemAnh() + sinhVien.getDiemVan()) ,
                sinhVien.getHinhAnh(),});
            stt++;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtMa = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        rdNam = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        rdNu = new javax.swing.JRadioButton();
        txtDiemToan = new javax.swing.JTextField();
        cboNamSinh = new javax.swing.JComboBox<>();
        txtDiemVan = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        btImage = new javax.swing.JButton();
        txtDiemAnh = new javax.swing.JTextField();
        txtTen = new javax.swing.JTextField();
        txtQueQuan = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSinhVien = new javax.swing.JTable();
        btDau = new javax.swing.JButton();
        btPrev = new javax.swing.JButton();
        btNext = new javax.swing.JButton();
        btLast = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnGhiFile = new javax.swing.JButton();
        btnTimKiem = new javax.swing.JButton();
        btnDocFile = new javax.swing.JButton();
        btThoat = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblDong = new javax.swing.JLabel();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Tên học sinh:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Giới tính:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Năm sinh");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Quê quán:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Điểm toán:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Điểm văn:");

        buttonGroup1.add(rdNam);
        rdNam.setText("Nam");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Điểm anh:");

        buttonGroup1.add(rdNu);
        rdNu.setText("Nữ");

        cboNamSinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023" }));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btImage.setFont(new java.awt.Font("Segoe UI", 0, 1)); // NOI18N
        btImage.setForeground(new java.awt.Color(255, 255, 255));
        btImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btImageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btImage, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btImage, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblSinhVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã hs", "Tên hs", "Giới tính", "Năm sinh", "Quê quán", "Điểm toán", "Điểm anh", "Điểm văn", "Tổng điểm", "Hình ảnh"
            }
        ));
        tblSinhVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSinhVienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSinhVien);

        btDau.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btDau.setText("|<");
        btDau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDauActionPerformed(evt);
            }
        });

        btPrev.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btPrev.setText("<<");
        btPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPrevActionPerformed(evt);
            }
        });

        btNext.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btNext.setText(">>");
        btNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNextActionPerformed(evt);
            }
        });

        btLast.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btLast.setText(">|");
        btLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLastActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnThem.setBackground(new java.awt.Color(249, 249, 249));
        btnThem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnThem.setForeground(new java.awt.Color(0, 0, 0));
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/addnew23.png"))); // NOI18N
        btnThem.setText("Add");
        btnThem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThemMouseClicked(evt);
            }
        });
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnXoa.setBackground(new java.awt.Color(249, 249, 249));
        btnXoa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnXoa.setForeground(new java.awt.Color(0, 0, 0));
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/delete.png"))); // NOI18N
        btnXoa.setText("Delete");
        btnXoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnXoaMouseClicked(evt);
            }
        });
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnSua.setBackground(new java.awt.Color(249, 249, 249));
        btnSua.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSua.setForeground(new java.awt.Color(0, 0, 0));
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-update-23.png"))); // NOI18N
        btnSua.setText("Save");
        btnSua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSuaMouseClicked(evt);
            }
        });
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnGhiFile.setBackground(new java.awt.Color(249, 249, 249));
        btnGhiFile.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnGhiFile.setForeground(new java.awt.Color(0, 0, 0));
        btnGhiFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ghifile.png"))); // NOI18N
        btnGhiFile.setText("Ghi file");
        btnGhiFile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGhiFileMouseClicked(evt);
            }
        });
        btnGhiFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGhiFileActionPerformed(evt);
            }
        });

        btnTimKiem.setBackground(new java.awt.Color(249, 249, 249));
        btnTimKiem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnTimKiem.setForeground(new java.awt.Color(0, 0, 0));
        btnTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-search-23.png"))); // NOI18N
        btnTimKiem.setText("Search");
        btnTimKiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTimKiemMouseClicked(evt);
            }
        });
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        btnDocFile.setBackground(new java.awt.Color(249, 249, 249));
        btnDocFile.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDocFile.setForeground(new java.awt.Color(0, 0, 0));
        btnDocFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/readfile.png"))); // NOI18N
        btnDocFile.setText("Đọc file");
        btnDocFile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDocFileMouseClicked(evt);
            }
        });
        btnDocFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDocFileActionPerformed(evt);
            }
        });

        btThoat.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-login-23.png"))); // NOI18N
        btThoat.setText("Thoát");
        btThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThoatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btThoat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTimKiem, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnThem, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGhiFile, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDocFile, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnThem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnXoa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSua)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTimKiem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGhiFile)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDocFile, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btThoat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Mã học sinh:");

        lblDong.setText("1 or 10");

        kGradientPanel1.setkEndColor(new java.awt.Color(0, 153, 51));
        kGradientPanel1.setkStartColor(new java.awt.Color(0, 0, 153));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Trang quản lý bảng điểm kỳ thi THPT");

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(8, 8, 8)
                                .addComponent(txtDiemToan, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25)
                                .addComponent(jLabel9)
                                .addGap(4, 4, 4)
                                .addComponent(txtDiemVan, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(20, 20, 20)
                                        .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(16, 16, 16)
                                        .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(39, 39, 39)
                                        .addComponent(rdNam)
                                        .addGap(9, 9, 9)
                                        .addComponent(rdNu))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(36, 36, 36)
                                        .addComponent(cboNamSinh, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(33, 33, 33)
                                        .addComponent(txtQueQuan, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblDong)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(3, 3, 3)
                                        .addComponent(txtDiemAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(btDau, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btPrev, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(btNext, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btLast, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 855, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel2))
                                    .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(rdNam)
                                    .addComponent(rdNu))
                                .addGap(19, 19, 19)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(cboNamSinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(txtQueQuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(74, 74, 74)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDiemToan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDiemVan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btDau, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btPrev, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btNext, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btLast, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblDong)
                                .addGap(49, 49, 49)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDiemAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblSinhVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSinhVienMouseClicked
        // TODO add your handling code here:
        int i = tblSinhVien.getSelectedRow();
        String ma = (String) tblSinhVien.getValueAt(i, 1);
        txtMa.setText(ma);
        String ten = (String) tblSinhVien.getValueAt(i, 2);
        txtTen.setText(ten);

        Integer namSinh = (Integer) tblSinhVien.getValueAt(i, 4);
        cboNamSinh.setSelectedItem(namSinh.toString());
        String queQuan = (String) tblSinhVien.getValueAt(i, 5);
        txtQueQuan.setText(queQuan);
        Double diemToan = (Double) tblSinhVien.getValueAt(i, 6);
        txtDiemToan.setText(diemToan.toString());
        Double diemAnh = (Double) tblSinhVien.getValueAt(i, 7);
        txtDiemAnh.setText(diemAnh.toString());
        Double diemVan = (Double) tblSinhVien.getValueAt(i, 8);
        txtDiemVan.setText(diemVan.toString());

        String tenAnh = (String) tblSinhVien.getValueAt(i, 10);
        String imagePath = tenAnh;  // Thay bằng đường dẫn thực tế

        // Đọc ảnh từ đường dẫn
        ImageIcon icon = new ImageIcon(imagePath);
        Image image = icon.getImage();

        // Lấy kích thước của JButton
        int width = btImage.getWidth();
        int height = btImage.getHeight();

        // Điều chỉnh kích thước ảnh để vừa với JButton
        Image newImage = image.getScaledInstance(97, 125, java.awt.Image.SCALE_SMOOTH);

        // Tạo ImageIcon mới từ ảnh đã điều chỉnh kích thước
        ImageIcon newIcon = new ImageIcon(newImage);

        // Hiển thị ảnh trên JButton
        btImage.setIcon(newIcon);
        btImage.setText(imagePath);

        String gioiTinh = (String) tblSinhVien.getValueAt(i, 3);
        if (gioiTinh.equals("Nam")) {
            rdNam.setSelected(true);
        } else {
            rdNu.setSelected(true);
        }
    }//GEN-LAST:event_tblSinhVienMouseClicked

    private void btnSuaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSuaMouseClicked
        // TODO add your handling code here:


          if(txtMa.getText().equals("")){
              JOptionPane.showMessageDialog(this, "Mã không được để trống");
          }else if(txtTen.getText().equals("")){
              JOptionPane.showMessageDialog(this, "Tên không được để trống");
          }else if(txtQueQuan.getText().equals("")){
              JOptionPane.showMessageDialog(this, "Quê quán không được để trống");
          }else if(txtDiemToan.getText().equals("")){
              JOptionPane.showMessageDialog(this, "Điểm Toán không được để trống");
          }else if(txtDiemVan.getText().equals("")){
              JOptionPane.showMessageDialog(this, "Điểm Văn không được để trống");
          }else if(txtDiemAnh.getText().equals("")){
              JOptionPane.showMessageDialog(this, "Điểm Anh không được để trống");
          }else if(!rdNam.isSelected()&& !rdNu.isSelected()){
              JOptionPane.showMessageDialog(this, "Giới tính không được để trống");
          
          }
          else{
                int i = tblSinhVien.getSelectedRow();

            String ma = txtMa.getText();
            String ten = txtTen.getText();
            String gioiTinh = "";
            String icon = btImage.getText();

            if (rdNam.isSelected()) {
                gioiTinh = "Nam";
            } else {
                gioiTinh = "Nữ";
            }
            Integer namSinh = Integer.parseInt(cboNamSinh.getSelectedItem().toString());
            String queQuan = txtQueQuan.getText();
            Float diemToan = Float.parseFloat(txtDiemToan.getText());
            Float diemAnh = Float.parseFloat(txtDiemAnh.getText());
            Float diemVan = Float.parseFloat(txtDiemVan.getText());
            SinhVien sinhVien = new SinhVien(ma, ten, gioiTinh, namSinh, queQuan, diemToan, diemVan, diemAnh, icon);
            Boolean check = qlsv.update(i, sinhVien);
            int kiemTra = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn sửa không?", " ", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (kiemTra == JOptionPane.YES_OPTION) {
                if (check) {
                    JOptionPane.showMessageDialog(this, "Update thành công");
                }
                loadData(qlsv.getListSinhVien());
            } else {
                return;
            }

          }
        

        

    }//GEN-LAST:event_btnSuaMouseClicked

    private void btnTimKiemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTimKiemMouseClicked
        // TODO add your handling code here:
        int i = tblSinhVien.getSelectedRow();
        String maCanTim = txtMa.getText();
        ArrayList<SinhVien> ketQuaTim = qlsv.timKiem(maCanTim);

        if (maCanTim.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhâp mã!");
        } else if (!ketQuaTim.isEmpty()) {
            loadData(ketQuaTim);
            for (SinhVien sinhVien : ketQuaTim) {
                String ten = sinhVien.getTenHS();
                txtTen.setText(ten);
                String gioiTinh = sinhVien.getGioiTinh();
                if (gioiTinh.equals("Nam")) {
                    rdNam.setSelected(true);
                } else {
                    rdNu.setSelected(true);
                }

                Integer namSinh = sinhVien.getNamSinh();
                cboNamSinh.setSelectedItem(namSinh);
                String queQuan = sinhVien.getQueQuan();
                txtQueQuan.setText(queQuan);
                Double diemToan = sinhVien.getDiemToan();
                txtDiemToan.setText(diemToan.toString());
                Double diemAnh = sinhVien.getDiemAnh();
                txtDiemAnh.setText(diemAnh.toString());
                Double diemVan = sinhVien.getDiemVan();
                txtDiemVan.setText(diemVan.toString());
            }
        } else {
            JOptionPane.showMessageDialog(this, "Không tìm thấy học sinh");
            loadData(qlsv.getListSinhVien());
        }
    }//GEN-LAST:event_btnTimKiemMouseClicked

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnThemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThemMouseClicked
        // TODO add your handling code here:
        String m = txtMa.getText();
        String ten = txtTen.getText();
        String gioitinh = " ";
        String icon = btImage.getText();

        int namsinh = Integer.parseInt(cboNamSinh.getSelectedItem().toString());
        String quequan = txtQueQuan.getText();
        Double toan, van, anh;
        if (rdNam.isSelected()) {
            gioitinh = "Nam";
        } else if (rdNu.isSelected()) {
            gioitinh = "Nữ";
        }

        

            try {
                toan = Double.parseDouble(txtDiemToan.getText());
                van = Double.parseDouble(txtDiemVan.getText());
                anh = Double.parseDouble(txtDiemAnh.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập điểm đúng đinh dạng");
                return;
            }
            if (m.isEmpty() || ten.isEmpty() || quequan.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Bạn cần nhập đầy đủ thông tin");
                return;
            } else if (toan > 10 || van > 10 || anh > 10) {
                JOptionPane.showMessageDialog(this, "Điểm cần phải < = 10");
                return;
            } else {

                ArrayList<SinhVien> list = qlsv.getListSinhVien();
                for (SinhVien sinhVien : list) {
                    if (sinhVien.getMaHS().equals(m)) {
                        JOptionPane.showMessageDialog(this, "Mã sinh viên " + m + " đã tồn tại. Vui lòng nhập mã sinh viên mới để thêm sinh viên");
                        return;
                    }
                }
               
                int kiemTra = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn thêm sinh viên với mã " + m + " không ?");
                if (kiemTra == JOptionPane.YES_OPTION) {
                    SinhVien sv = new SinhVien(m, ten, gioitinh, namsinh, quequan, toan, van, anh, icon);
                    Boolean checkAdd = qlsv.AddNew(sv);
                    if (checkAdd) {
                        JOptionPane.showMessageDialog(this, "Thêm thành công");
                        loadData(qlsv.getListSinhVien());
                    }
                }else{
                    return;
                }
            }



        


    }//GEN-LAST:event_btnThemMouseClicked

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnThemActionPerformed

    private void btnXoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXoaMouseClicked
        // TODO add your handling code here:
        int i = tblSinhVien.getSelectedRow();

        
            int kiemTra = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xóa học sinh với mã " + txtMa.getText() + " không ?");
            if (kiemTra == JOptionPane.YES_OPTION) {
                boolean xoa = qlsv.delete(i);
                if (xoa) {

                    JOptionPane.showMessageDialog(this, "Xóa thành công học sinh có mã  " + txtMa.getText());
                }
                loadData(qlsv.getListSinhVien());
            }

        
    }//GEN-LAST:event_btnXoaMouseClicked

    private void btImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btImageActionPerformed
        // TODO add your handling code here:
        JFileChooser dlg = new JFileChooser();
        dlg.showOpenDialog(this);

        File selectedFile = dlg.getSelectedFile();
//        if (selectedFile != null) {
//            String tenAnh = selectedFile.getName(); // Lấy tên file ảnh
//
//            ImageIcon icon = new ImageIcon(selectedFile.getAbsolutePath());
//            Image newImage = icon.getImage().getScaledInstance(97, 125, Image.SCALE_SMOOTH);
//            ImageIcon newIcon = new ImageIcon(newImage);
//
//            btImage.setIcon(newIcon);
//            btImage.setText(tenAnh); // Set text thành tên file ảnh
//        } else {
//            // Người dùng đã cancel hoặc không chọn file, xử lý tùy theo yêu cầu của bạn
//        }

        String path = selectedFile.getAbsolutePath();

        ImageIcon icon = new ImageIcon(path);
        Image newImage = icon.getImage().getScaledInstance(97, 125, Image.SCALE_SMOOTH);
        ImageIcon newIcon = new ImageIcon(newImage);

        btImage.setIcon(newIcon);
        btImage.setText(path); // Set text thành đường dẫn
    }//GEN-LAST:event_btImageActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSuaActionPerformed
    void ghiFile() throws IOException {
        File file = new File("agile.txt");
        if (!file.exists()) {
            file.createNewFile();
        }
        FileOutputStream fos = new FileOutputStream(file);
        ObjectOutputStream oos = new ObjectOutputStream(fos);
        ArrayList<SinhVien> list = qlsv.getListSinhVien();
        for (SinhVien sinhVien : list) {
            oos.writeObject(sinhVien);
        }
        oos.close();
        fos.close();

    }
    

    
//    void ghiFile(File file) throws IOException {
//    try (FileOutputStream fos = new FileOutputStream(file);
//         ObjectOutputStream oos = new ObjectOutputStream(fos)) {
//
//        ArrayList<SinhVien> list = qlsv.getListSinhVien();
//        for (SinhVien sinhVien : list) {
//            oos.writeObject(sinhVien);
//        }
//
//    } catch (IOException ex) {
//        // Handle the exception or log it
//        ex.printStackTrace();
//        throw ex; // Rethrow the exception if needed
//    }
//}
    private void btnGhiFileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGhiFileMouseClicked

            int kiemTra = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn ghi file không?", " ", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (kiemTra == JOptionPane.YES_OPTION) {
                try {
                    // TODO add your handling code here:
                    ghiFile();
                    JOptionPane.showMessageDialog(this, "Ghi File thành công");
                } catch (IOException ex) {
                    Logger.getLogger(QuanLyDiemView.class.getName()).log(Level.SEVERE, null, ex);
                }

            } else {
                return;
            }


        
    

//    int kiemTra = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn ghi file không?", " ", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
//
//    if (kiemTra == JOptionPane.YES_OPTION) {
//        JFileChooser fileChooser = new JFileChooser();
//        fileChooser.setDialogTitle("Chọn vị trí và nhập tên tệp");
//        FileNameExtensionFilter filter = new FileNameExtensionFilter("Text Files", "txt");
//        fileChooser.setFileFilter(filter);
//
//        int userSelection = fileChooser.showSaveDialog(null);
//
//        if (userSelection == JFileChooser.APPROVE_OPTION) {
//            File fileToSave = fileChooser.getSelectedFile();
//
//            try {
//                if (fileToSave.createNewFile()) {
//                    System.out.println("Tệp đã được tạo thành công.");
//                    try {
//                        ghiFile(fileToSave);
//                        JOptionPane.showMessageDialog(this, "Ghi File thành công");
//                    } catch (IOException ex) {
//                        Logger.getLogger(QuanLyDiemView.class.getName()).log(Level.SEVERE, null, ex);
//                    }
//                }
//            } catch (IOException e) {
//                System.out.println("Đã xảy ra lỗi khi tạo tệp: " + e.getMessage());
//            }
//        } else if (userSelection == JFileChooser.CANCEL_OPTION) {
//            System.out.println("Hủy tạo tệp.");
//        }
//    } else {
//        return;
//    }

        

    }//GEN-LAST:event_btnGhiFileMouseClicked
    void docFile() throws FileNotFoundException, IOException, ClassNotFoundException {
        DefaultTableModel model = (DefaultTableModel) tblSinhVien.getModel();
        model.setRowCount(0);
        File file = new File("agile.txt");
        if (!file.exists()) {
            System.out.println("Khong tim thay file");
            return;
        }
        FileInputStream fis = new FileInputStream(file);
        ObjectInputStream ois = new ObjectInputStream(fis);
        ArrayList<SinhVien> list = new ArrayList<>();
//        ArrayList<SinhVien> list = qlsv.getListSinhVien();
        while (fis.available() > 0) {
            list.add((SinhVien) ois.readObject());
        }
        ois.close();
        fis.close();
        
        qlsv.getListSinhVien().clear();
        qlsv.getListSinhVien().addAll(list);
        loadData(list);

    }
    
    
    
    private void btnDocFileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDocFileMouseClicked

            int kiemTra = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn đọc file không?", " ", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (kiemTra == JOptionPane.YES_OPTION) {
                try {
                    // TODO add your handling code here:
                    docFile();
                } catch (IOException ex) {
                    Logger.getLogger(QuanLyDiemView.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(QuanLyDiemView.class.getName()).log(Level.SEVERE, null, ex);
                }

            } else {
                return;
            }

        

    }//GEN-LAST:event_btnDocFileMouseClicked

    public void fillSinhVien(int index) {
        txtMa.setText(qlsv.getListSinhVien().get(index).getMaHS());
        txtTen.setText(qlsv.getListSinhVien().get(index).getTenHS());
        if (qlsv.getListSinhVien().get(index).getGioiTinh().equals("Nam")) {
            rdNam.setSelected(true);
        } else {
            rdNu.setSelected(true);
        }
        cboNamSinh.setSelectedItem(String.valueOf(qlsv.getListSinhVien().get(index).getNamSinh()));
        txtQueQuan.setText(qlsv.getListSinhVien().get(index).getQueQuan());
        txtDiemToan.setText(String.valueOf(qlsv.getListSinhVien().get(index).getDiemToan()));
        txtDiemVan.setText(String.valueOf(qlsv.getListSinhVien().get(index).getDiemVan()));
        txtDiemAnh.setText(String.valueOf(qlsv.getListSinhVien().get(index).getDiemAnh()));
//        btImage.setText(qlsv.getListSinhVien().get(index).getHinhAnh
        String tenAnh = (String) tblSinhVien.getValueAt(index, 10);
        String imagePath = tenAnh;  // Thay bằng đường dẫn thực tế

        // Đọc ảnh từ đường dẫn
        ImageIcon icon = new ImageIcon(imagePath);
        Image image = icon.getImage();

        // Lấy kích thước của JButton
        int width = btImage.getWidth();
        int height = btImage.getHeight();

        // Điều chỉnh kích thước ảnh để vừa với JButton
        Image newImage = image.getScaledInstance(97, 125, java.awt.Image.SCALE_SMOOTH);

        // Tạo ImageIcon mới từ ảnh đã điều chỉnh kích thước
        ImageIcon newIcon = new ImageIcon(newImage);

        // Hiển thị ảnh trên JButton
        btImage.setIcon(newIcon);
        btImage.setText(imagePath);

    }
    private void btDauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDauActionPerformed
        // TODO add your handling code here:
        int index = 0;
        tblSinhVien.setRowSelectionInterval(index, index);
        fillSinhVien(index);
        lblDong.setText(LayThongTinTable(index, tblSinhVien.getRowCount()));
    }//GEN-LAST:event_btDauActionPerformed

    private void btLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLastActionPerformed
        // TODO add your handling code here:
        ArrayList<SinhVien> list = qlsv.getListSinhVien();
        int index = list.size() - 1;
        tblSinhVien.setRowSelectionInterval(index, index);
        fillSinhVien(index);
        lblDong.setText(LayThongTinTable(index, tblSinhVien.getRowCount()));
    }//GEN-LAST:event_btLastActionPerformed

    private void btPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPrevActionPerformed
        // TODO add your handling code here:
        int index = tblSinhVien.getSelectedRow();
        if (index == 0) {
            ArrayList<SinhVien> list = qlsv.getListSinhVien();
            index = list.size() - 1;
        } else {
            index--;
        }
        tblSinhVien.setRowSelectionInterval(index, index);
        fillSinhVien(index);
        lblDong.setText(LayThongTinTable(index, tblSinhVien.getRowCount()));
    }//GEN-LAST:event_btPrevActionPerformed

    private void btNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNextActionPerformed
        // TODO add your handling code here:
        int index = tblSinhVien.getSelectedRow();
        ArrayList<SinhVien> list = qlsv.getListSinhVien();
        if (index == qlsv.getListSinhVien().size() - 1) {
            index = 0;
        } else {
            index++;
        }
        tblSinhVien.setRowSelectionInterval(index, index);
        fillSinhVien(index);
        lblDong.setText(LayThongTinTable(index, tblSinhVien.getRowCount()));
    }//GEN-LAST:event_btNextActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTimKiemActionPerformed
    
    
    private void btThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThoatActionPerformed
        // TODO add your handling code here:
        login login =  new login();
        login.setVisible(true);
        dispose();
    }//GEN-LAST:event_btThoatActionPerformed

    private void btnDocFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDocFileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDocFileActionPerformed

    private void btnGhiFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGhiFileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGhiFileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(new FlatMacLightLaf());
        } catch (Exception ex) {
            System.err.println("Failed to initialize LaF");
        }
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyDiemView().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btDau;
    private javax.swing.JButton btImage;
    private javax.swing.JButton btLast;
    private javax.swing.JButton btNext;
    private javax.swing.JButton btPrev;
    private javax.swing.JButton btThoat;
    private javax.swing.JButton btnDocFile;
    private javax.swing.JButton btnGhiFile;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cboNamSinh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JLabel lblDong;
    private javax.swing.JRadioButton rdNam;
    private javax.swing.JRadioButton rdNu;
    private javax.swing.JTable tblSinhVien;
    private javax.swing.JTextField txtDiemAnh;
    private javax.swing.JTextField txtDiemToan;
    private javax.swing.JTextField txtDiemVan;
    private javax.swing.JTextField txtMa;
    private javax.swing.JTextField txtQueQuan;
    private javax.swing.JTextField txtTen;
    // End of variables declaration//GEN-END:variables
}
